name: codereview

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'

      - name: Install SonarQube Scanner
        run: |
          curl -L -o sonar-scanner-cli-7.0.0.4796-linux-x64.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.0.4796-linux-x64.zip
          unzip sonar-scanner-cli-7.0.0.4796-linux-x64.zip
          mv sonar-scanner-7.0.0.4796-linux-x64 /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: SonarQube Scan
        run: |
          sonar-scanner -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



  eslint-prettier:
    name: ESLint and Prettier
    runs-on: ubuntu-latest
    needs: sonarqube
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Run ESLint
        run: |
          cd server
          npx eslint . --ext .js,.ts,.jsx,.tsx --fix

      - name: Run Prettier
        run: |
          cd server
          npx prettier --check . 

      - name: Fix code with Prettier
        run: |
          cd server
          npx prettier --write .
